### PR TITLE
Remove multimap dependency

### PR DESCRIPTION
**Pull request by mqp**
This wasn't really pulling its weight, and killing it decreases the surface area for bugs like #62.

Also now we don't leak an empty vec in maps for every user and room that ever exists which is nice.

### CODE REVIEW

**Comment by vincentfretin** [comment]
Nice, the changes looks great. I'll test to build this today with my additional fix about the publisher reconnecting.

**Comment by vincentfretin** [comment]
I actually deployed just this branch on my server and asked everyone to do some tests. I'll let you know if there is any issue.

**Comment by mqp** [comment]
OK, I'll merge it if it seems like it's working well for you.

**Comment by vincentfretin** [comment]
My colleague did the tests with all his devices yesterday. He didn't have any weird issues, so that's cool. Yes, you can merge. Thank you very much!

**Comment by vincentfretin** [comment]
Still no issues. :)

**Pull request merged**
